INSERT INTO LOCATION_DETAILS VALUES('L101','DALLAS LOVE FIELD AIRPORT',
'Herb Kelleher Way','Dallas','Texas',75235);
INSERT INTO LOCATION_DETAILS VALUES('L102','LOS ANGELES INTL AIRPORT',
'World Way','Los Angeles','California',90045);
INSERT INTO LOCATION_DETAILS VALUES('L103','DALLAS/ FORT WORTH INTL AIRPORT',
'International Pkwy','DFW Airport','Texas',75261);
INSERT INTO LOCATION_DETAILS VALUES('L104','WEST HOUSTON AIRPORT',
'Groschke Rd','Houston','Texas',77094);
INSERT INTO LOCATION_DETAILS VALUES('L105','WASHINGTON DULLES INTL AIRPORT',
'Saarinen Cir','Dulles','Virginia',20166);
INSERT INTO LOCATION_DETAILS VALUES('L106','NEWARK LIBERTY INTL AIRPORT',
'Brewster Rd','Newark','New Jersey',07114);
INSERT INTO LOCATION_DETAILS VALUES('L107','SALT LAKE CITY INTL AIRPORT',
'N Terminal Dr','Salt Lake City','Utah',84122);