INSERT INTO RENTAL_CAR_INSURANCE VALUES('I201', 'COLLISION DAMAGE WAIVER',
'Covers theft and total damage to the rental car',15);
INSERT INTO RENTAL_CAR_INSURANCE VALUES('I202',
'SUPPLEMENTAL LIABILITY PROTECTION', 'Covers damage done to others',12);
INSERT INTO RENTAL_CAR_INSURANCE VALUES('I203',
'PERSONAL ACCIDENT INSURANCE', 'Covers medical costs for driver and passengers',10);
INSERT INTO RENTAL_CAR_INSURANCE VALUES('I204',
'PERSONAL EFFECTS COVERAGE', 'Covers theft of personal belongings',5);